name: infra-ci
on:
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/infra-ci.yml'
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra-ci.yml'
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.12.2
  TF_WORKDIR: infra/envs/dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # for OIDC auth
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform validate

      - name: Terraform Plan (PR only)
        if: github.event_name == 'pull_request'
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform plan -no-color -input=false

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform apply -auto-approve -input=false
