apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels: { app: frontend }
spec:
  selector: { app: frontend }
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP